BGP negotiated timers. Display BGP timers in CLI.
MERAprojects/ops-cli pull request #10
Opened 2016-09-13 13:54 UTC by xschily

Tags: fix, dev, Github issue #9

Change-Id: I275a2a889faf719ed37fbc0e53e6952efeac42cc
Signed-off-by: Ilya Schepin <ischepin@mera.ru>

CLI command `show ip bgp neighbors` will now show per-neighbor (or per-peer-group) configured BGP timers (keepalive and holdtime) and per-neighbor negotiated timers.  
New status field `negotiated_timers` was added to OVSDB table BGP_Neighbor  
Priority of timer parameters as follows:  
Per-peer-group configured > per-neighbor configured > per-router configured > default values  
Depends on MERAprojects/ops-quagga#24 and MERAprojects/ops#2

2016-10-10 10:26 UTC, apolovin commented on vtysh/bgp_vty.c
> +    if (ovs_bgp_neighbor->n_negotiated_timers) {
suspicious code: check is for non-zero, but 2 array elements are acessed

2016-10-10 10:27 UTC, apolovin requested changes
suspicious array access. Explain or correct.

2016-10-10 15:17 UTC, vkarpov commented on vtysh/bgp_vty.c
>          }
It may be done so:

`-             show_one_bgp_neighbor(vty, ovs_bgp_router->key_bgp_neighbors[i],`
`-                                  ovs_bgp_router->value_bgp_neighbors[i]);`
`+             show_one_bgp_neighbor(vty, ovs_bgp_router);`

2016-10-20 11:39 UTC, apolovin approved these changes

2016-11-08 09:51 UTC, vkarpov commented
Merged into meraswitch/devel/master.

2016-11-08 09:51 UTC, closed without merging