Issue #20: Possible to remove private AS for IBGP peer
MERAprojects/ops-cli pull request #29
Opened 2017-02-15 14:31 UTC by lyubov-popova

Initial commit for BGP commands validation (added validation of remove-private-AS).

Issue #20: Possible to remove private AS for IBGP peer
Change-Id: Ic5fcf894f6c509e888256b59b849f7cc8f9437c6

2017-02-16 11:31 UTC, AKochin commented on vtysh/bgp_vty.c
> +    if (result == BGP_SUCCESS)
How about case (result) here?

2017-02-16 16:25 UTC, stroykov commented on vtysh/bgp_vty.c
> +        vty_out(vty, "Unknown BGP error code = %d\n", result);
transaction is lost here?

2017-02-16 16:27 UTC, stroykov requested changes
leave only the changes needed to fix the issue.
restore  other source code

2017-02-16 16:37 UTC, AKochin commented
This commit is a part of a big task of validation of BGP commands got from CLI. These changes are start point of it so this code just need to be adjusted not removed.

2017-02-17 13:34 UTC, lyubov-popova commented
Hi,
Comments after review were applied. Can you please review it again?
Summary of changes:
1) Validation for remove-private-AS command (check for IBGP peer)
2) remove-private-AS is deleted if remote AS is changed from external to internal
3) Error code constants are introduced instead of repeated error text
4) Check for ovs_bgp_neighbor was added if missed. Using ABORT_DB_TXN if BGP neighbor is not configured:
         ovs_bgp_neighbor = get_bgp_neighbor_with_bgp_router_and_ipaddr(bgp_router_context, peer_str);
         if (ovs_bgp_neighbor) {
              /* write to the DB */
              ovsrec_bgp_neighbor_set_bfd_fallover_enable(ovs_bgp_neighbor, &is_set_bfd, 1);		              
          }
         **else {
             ABORT_DB_TXN(txn, BGP_ERR_NEIGHBOR_IS_NOT_CONFIGURED);
 	}**

2017-02-21 07:25 UTC, stroykov commented on vtysh/bgp_vty.c
> +is_ibgp_peer(const struct ovsrec_bgp_neighbor *ovs_bgp_neighbor,
from the name semantic, the function must take bgp and neighbor input parameters and decide, if that neighbor is of ibgp type.

2017-02-21 12:44 UTC, lyubov-popova commented on vtysh/bgp_vty.c
> +is_ibgp_peer(const struct ovsrec_bgp_neighbor *ovs_bgp_neighbor,
Do you mean changing parameters in the function or function name?

Tried to change parameters in following way:
```
static bool is_ibgp_peer(const struct ovsrec_bgp_neighbor *ovs_bgp_neighbor,
                                      const struct ovsrec_bgp_router *bgp_router_context)
```

But, as I understand, struct ovsrec_bgp_router does not contain asn, it is stored in `ovs_vrf->key_bgp_routers[j]`
E.g., in vtysh_router_context_bgp_clientcallback function https://github.com/MERAprojects/ops-cli/blob/meraswitch/devel/master/vtysh/vtysh_ovsdb_router_context.c

I can write a comment describing parameters in is_ibgp_peer function.

2017-02-22 06:42 UTC, stroykov commented on vtysh/bgp_vty.c
> +is_ibgp_peer(const struct ovsrec_bgp_neighbor *ovs_bgp_neighbor,
Leave as it is, but change parameter name asn to own_asn

2017-02-23 08:04 UTC, stroykov approved these changes

2017-02-28 08:48 UTC, merged